// GENERATED by web/tools/gen_offsets.py - do not edit by hand.
(function (root) {
    'use strict';
    var data = {
 "_comment": "GENERATED by web/tools/gen_offsets.py - do not edit by hand.",
 "generated_from": "addac511_V2-44-gba49-dirty.elf",
 "structs": {
  "Preset": {
   "size": 18416,
   "fields": [
    {
     "name": "version",
     "offset": 0,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "id",
     "offset": 4,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "name",
     "offset": 8,
     "size": 20,
     "type": "char",
     "elem_size": 1,
     "dims": [
      20
     ]
    },
    {
     "name": "n_assigns",
     "offset": 28,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "current_state",
     "offset": 32,
     "size": 16,
     "type": "pointer",
     "elem_size": 4,
     "dims": [
      4
     ]
    },
    {
     "name": "channel_states_balance",
     "offset": 48,
     "size": 48,
     "type": "States_balance",
     "elem_size": 12,
     "dims": [
      4
     ]
    },
    {
     "name": "states_random_active",
     "offset": 96,
     "size": 4,
     "type": "bool",
     "elem_size": 1,
     "dims": [
      4
     ]
    },
    {
     "name": "cv_mode",
     "offset": 100,
     "size": 16,
     "type": "CVOutMode",
     "elem_size": 4,
     "dims": [
      4
     ]
    },
    {
     "name": "voltage_mode",
     "offset": 116,
     "size": 48,
     "type": "VoltageMode",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_min",
     "offset": 164,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_max",
     "offset": 212,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_rest",
     "offset": 260,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_nvsteps",
     "offset": 308,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_quantization_scale",
     "offset": 356,
     "size": 48,
     "type": "pointer",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_quantize_post",
     "offset": 404,
     "size": 12,
     "type": "bool",
     "elem_size": 1,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_root_note",
     "offset": 416,
     "size": 240,
     "type": "note_t",
     "elem_size": 20,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_quantize_rel_source",
     "offset": 656,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_quantize_transpose_mode",
     "offset": 704,
     "size": 48,
     "type": "TransposeMode",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_quantize_transpose_semitones",
     "offset": 752,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_quantize_transpose_scale_degrees",
     "offset": 800,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_quantize_transpose_cents",
     "offset": 848,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_quantize_transpose_octaves",
     "offset": 896,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_gate_size",
     "offset": 944,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_gate_probability",
     "offset": 992,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_gate_skip_steps",
     "offset": 1040,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_probability",
     "offset": 1088,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_skip_steps",
     "offset": 1136,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_probability_apply_to_cv_and_gate",
     "offset": 1184,
     "size": 12,
     "type": "bool",
     "elem_size": 1,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_p_linearity",
     "offset": 1196,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_distribution",
     "offset": 1244,
     "size": 144,
     "type": "distribution_t",
     "elem_size": 12,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_weight",
     "offset": 1388,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_smooth_curve",
     "offset": 1436,
     "size": 48,
     "type": "SmoothCurve",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_smooth_duration",
     "offset": 1484,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_smooth_resolution",
     "offset": 1532,
     "size": 48,
     "type": "BitResolution",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_smooth_step_mode",
     "offset": 1580,
     "size": 48,
     "type": "SmoothStepMode",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_smooth_v_steps",
     "offset": 1628,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_smooth_step_time",
     "offset": 1676,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_smooth_triggers_gate",
     "offset": 1724,
     "size": 12,
     "type": "uint8_t",
     "elem_size": 1,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "v_range_lock",
     "offset": 1736,
     "size": 12,
     "type": "bool",
     "elem_size": 1,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_min",
     "offset": 1748,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_max",
     "offset": 1796,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_min_attack",
     "offset": 1844,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_max_attack",
     "offset": 1892,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_min_sustain",
     "offset": 1940,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_max_sustain",
     "offset": 1988,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_min_release",
     "offset": 2036,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_max_release",
     "offset": 2084,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_min_rest",
     "offset": 2132,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_max_rest",
     "offset": 2180,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_min_attack_rel",
     "offset": 2228,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_max_attack_rel",
     "offset": 2276,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_min_sustain_rel",
     "offset": 2324,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_max_sustain_rel",
     "offset": 2372,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_min_release_rel",
     "offset": 2420,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_max_release_rel",
     "offset": 2468,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "envelope_mode",
     "offset": 2516,
     "size": 48,
     "type": "EnvelopeMode",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "envelope_scale_min",
     "offset": 2564,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "envelope_scale_max",
     "offset": 2612,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "envelope_attack_shape",
     "offset": 2660,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "envelope_release_shape",
     "offset": 2708,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "envelope_size_src",
     "offset": 2756,
     "size": 48,
     "type": "ClockSource",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "bpm_mode",
     "offset": 2804,
     "size": 12,
     "type": "bool",
     "elem_size": 1,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "bpm",
     "offset": 2816,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "time_divisions",
     "offset": 2864,
     "size": 1056,
     "type": "time_div_t",
     "elem_size": 8,
     "dims": [
      4,
      3,
      11
     ]
    },
    {
     "name": "t_distribution",
     "offset": 3920,
     "size": 144,
     "type": "distribution_t",
     "elem_size": 12,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_weight",
     "offset": 4064,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "clock",
     "offset": 4112,
     "size": 48,
     "type": "ClockSource",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "clock_use_time",
     "offset": 4160,
     "size": 12,
     "type": "bool",
     "elem_size": 1,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "clock_use_bpm",
     "offset": 4172,
     "size": 12,
     "type": "bool",
     "elem_size": 1,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "clock_mult_div",
     "offset": 4184,
     "size": 48,
     "type": "ClockMultDiv",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "t_range_relative",
     "offset": 4232,
     "size": 12,
     "type": "bool",
     "elem_size": 1,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "sync_or_zero_probability",
     "offset": 4244,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "seq_steps",
     "offset": 4292,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "seq_voltage",
     "offset": 4340,
     "size": 1536,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3,
      32
     ]
    },
    {
     "name": "seq_gate_on",
     "offset": 5876,
     "size": 384,
     "type": "bool",
     "elem_size": 1,
     "dims": [
      4,
      3,
      32
     ]
    },
    {
     "name": "seq_time",
     "offset": 6260,
     "size": 1536,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3,
      32
     ]
    },
    {
     "name": "seq_bpm_div",
     "offset": 7796,
     "size": 3072,
     "type": "time_div_t",
     "elem_size": 8,
     "dims": [
      4,
      3,
      32
     ]
    },
    {
     "name": "seq_step_probability",
     "offset": 10868,
     "size": 1536,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3,
      32
     ]
    },
    {
     "name": "seq_step_mode",
     "offset": 12404,
     "size": 48,
     "type": "StepMode",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "seq_step_dir",
     "offset": 12452,
     "size": 48,
     "type": "StepDir",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "seq_offset",
     "offset": 12500,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "seq_mode",
     "offset": 12548,
     "size": 12,
     "type": "SequencerMode",
     "elem_size": 1,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "seq_step_once",
     "offset": 12560,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "seq_step_always",
     "offset": 12608,
     "size": 48,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "cva",
     "offset": 12656,
     "size": 2048,
     "type": "cv_assignment",
     "elem_size": 32,
     "dims": [
      64
     ]
    },
    {
     "name": "lga",
     "offset": 14704,
     "size": 2220,
     "type": "logic_assignment",
     "elem_size": 740,
     "dims": [
      3
     ]
    },
    {
     "name": "custom_scale",
     "offset": 16924,
     "size": 608,
     "type": "custom_scale_t",
     "elem_size": 76,
     "dims": [
      8
     ]
    },
    {
     "name": "note_probabilities",
     "offset": 17532,
     "size": 576,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3,
      12
     ]
    },
    {
     "name": "quantization_rounding",
     "offset": 18108,
     "size": 12,
     "type": "QuantizeRounding",
     "elem_size": 1,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "current_state_id",
     "offset": 18120,
     "size": 16,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4
     ]
    },
    {
     "name": "v_quantization_scale_id",
     "offset": 18136,
     "size": 48,
     "type": "int",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "time_mode",
     "offset": 18184,
     "size": 48,
     "type": "TimeMode",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "counter",
     "offset": 18232,
     "size": 3,
     "type": "uint8_t",
     "elem_size": 1,
     "dims": [
      3
     ]
    },
    {
     "name": "lga_bpm_mult_div",
     "offset": 18236,
     "size": 12,
     "type": "int",
     "elem_size": 4,
     "dims": [
      3
     ]
    },
    {
     "name": "lga_bpm_gate_trigger_mode",
     "offset": 18248,
     "size": 12,
     "type": "int",
     "elem_size": 4,
     "dims": [
      3
     ]
    },
    {
     "name": "lga_counter_gate_trigger_mode",
     "offset": 18260,
     "size": 12,
     "type": "int",
     "elem_size": 4,
     "dims": [
      3
     ]
    },
    {
     "name": "bpm_beat_note",
     "offset": 18272,
     "size": 96,
     "type": "time_div_t",
     "elem_size": 8,
     "dims": [
      4,
      3
     ]
    },
    {
     "name": "gate_size_deviation",
     "offset": 18368,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4,
      3
     ]
    }
   ]
  },
  "PresetsCommon": {
   "size": 148,
   "fields": [
    {
     "name": "version",
     "offset": 0,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "preset_slot_size",
     "offset": 4,
     "size": 4,
     "type": "uint32_t",
     "elem_size": 4
    },
    {
     "name": "npresets",
     "offset": 8,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "selected",
     "offset": 12,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "preset",
     "offset": 16,
     "size": 68,
     "type": "uint32_t",
     "elem_size": 4,
     "dims": [
      17
     ]
    },
    {
     "name": "check",
     "offset": 84,
     "size": 40,
     "type": "char",
     "elem_size": 1,
     "dims": [
      40
     ]
    },
    {
     "name": "screensaver_mode",
     "offset": 124,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "screensaver_wait_time",
     "offset": 128,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "auto_return_to_main",
     "offset": 132,
     "size": 1,
     "type": "bool",
     "elem_size": 1
    },
    {
     "name": "time_auto_return_to_main",
     "offset": 136,
     "size": 4,
     "type": "uint32_t",
     "elem_size": 4
    },
    {
     "name": "cv_before_gate",
     "offset": 140,
     "size": 1,
     "type": "bool",
     "elem_size": 1
    },
    {
     "name": "exists",
     "offset": 144,
     "size": 4,
     "type": "pointer",
     "elem_size": 4
    }
   ]
  },
  "CalibrationData": {
   "size": 24,
   "fields": [
    {
     "name": "channel_calibration_offsets",
     "offset": 0,
     "size": 8,
     "type": "int16_t",
     "elem_size": 2,
     "dims": [
      4
     ]
    },
    {
     "name": "channel_calibration_gains",
     "offset": 8,
     "size": 16,
     "type": "float",
     "elem_size": 4,
     "dims": [
      4
     ]
    }
   ]
  },
  "PresetTrailer": {
   "size": 16,
   "fields": [
    {
     "name": "magic",
     "offset": 0,
     "size": 4,
     "type": "uint32_t",
     "elem_size": 4
    },
    {
     "name": "format",
     "offset": 4,
     "size": 4,
     "type": "uint32_t",
     "elem_size": 4
    },
    {
     "name": "payload_size",
     "offset": 8,
     "size": 4,
     "type": "uint32_t",
     "elem_size": 4
    },
    {
     "name": "crc32",
     "offset": 12,
     "size": 4,
     "type": "uint32_t",
     "elem_size": 4
    }
   ]
  },
  "cv_assignment": {
   "size": 32,
   "fields": [
    {
     "name": "id",
     "offset": 0,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "input",
     "offset": 4,
     "size": 1,
     "type": "uint8_t",
     "elem_size": 1
    },
    {
     "name": "channel",
     "offset": 5,
     "size": 1,
     "type": "uint8_t",
     "elem_size": 1
    },
    {
     "name": "gain",
     "offset": 8,
     "size": 4,
     "type": "float",
     "elem_size": 4
    },
    {
     "name": "offset",
     "offset": 12,
     "size": 4,
     "type": "float",
     "elem_size": 4
    },
    {
     "name": "inverted",
     "offset": 16,
     "size": 1,
     "type": "bool",
     "elem_size": 1
    },
    {
     "name": "function_type",
     "offset": 20,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "function_id",
     "offset": 24,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "state",
     "offset": 28,
     "size": 4,
     "type": "int",
     "elem_size": 4
    }
   ]
  },
  "logic_assignment": {
   "size": 740,
   "fields": [
    {
     "name": "id",
     "offset": 0,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "channel",
     "offset": 4,
     "size": 1,
     "type": "uint8_t",
     "elem_size": 1
    },
    {
     "name": "state",
     "offset": 5,
     "size": 1,
     "type": "uint8_t",
     "elem_size": 1
    },
    {
     "name": "n_lines",
     "offset": 8,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "lg_line",
     "offset": 12,
     "size": 640,
     "type": "logic_line",
     "elem_size": 32,
     "dims": [
      20
     ]
    },
    {
     "name": "out",
     "offset": 652,
     "size": 1,
     "type": "uint8_t",
     "elem_size": 1
    },
    {
     "name": "op",
     "offset": 656,
     "size": 80,
     "type": "LogicOp",
     "elem_size": 4,
     "dims": [
      20
     ]
    },
    {
     "name": "value",
     "offset": 736,
     "size": 1,
     "type": "bool",
     "elem_size": 1
    }
   ]
  },
  "logic_line": {
   "size": 32,
   "fields": [
    {
     "name": "id",
     "offset": 0,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "x_input",
     "offset": 4,
     "size": 1,
     "type": "uint8_t",
     "elem_size": 1
    },
    {
     "name": "y_input",
     "offset": 5,
     "size": 1,
     "type": "uint8_t",
     "elem_size": 1
    },
    {
     "name": "output",
     "offset": 8,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "result",
     "offset": 12,
     "size": 1,
     "type": "bool",
     "elem_size": 1
    },
    {
     "name": "x_value",
     "offset": 13,
     "size": 1,
     "type": "bool",
     "elem_size": 1
    },
    {
     "name": "op",
     "offset": 16,
     "size": 4,
     "type": "LogicOp",
     "elem_size": 4
    },
    {
     "name": "y_value",
     "offset": 20,
     "size": 1,
     "type": "bool",
     "elem_size": 1
    },
    {
     "name": "aux_count",
     "offset": 24,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "continuous_update",
     "offset": 28,
     "size": 1,
     "type": "bool",
     "elem_size": 1
    }
   ]
  },
  "custom_scale_t": {
   "size": 76,
   "fields": [
    {
     "name": "id",
     "offset": 0,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "name",
     "offset": 4,
     "size": 20,
     "type": "char",
     "elem_size": 1,
     "dims": [
      20
     ]
    },
    {
     "name": "semitones",
     "offset": 24,
     "size": 48,
     "type": "float",
     "elem_size": 4,
     "dims": [
      12
     ]
    },
    {
     "name": "n_semitones",
     "offset": 72,
     "size": 4,
     "type": "int",
     "elem_size": 4
    }
   ]
  },
  "note_t": {
   "size": 20,
   "fields": [
    {
     "name": "semitone",
     "offset": 0,
     "size": 4,
     "type": "int",
     "elem_size": 4
    },
    {
     "name": "cents",
     "offset": 4,
     "size": 4,
     "type": "float",
     "elem_size": 4
    },
    {
     "name": "v",
     "offset": 8,
     "size": 4,
     "type": "float",
     "elem_size": 4
    },
    {
     "name": "name",
     "offset": 12,
     "size": 8,
     "type": "char",
     "elem_size": 1,
     "dims": [
      8
     ]
    }
   ]
  },
  "distribution_t": {
   "size": 12,
   "fields": [
    {
     "name": "mode",
     "offset": 0,
     "size": 4,
     "type": "DistributionMode",
     "elem_size": 4
    },
    {
     "name": "pos",
     "offset": 4,
     "size": 4,
     "type": "float",
     "elem_size": 4
    },
    {
     "name": "spread",
     "offset": 8,
     "size": 4,
     "type": "float",
     "elem_size": 4
    }
   ]
  },
  "time_div_t": {
   "size": 8,
   "fields": [
    {
     "name": "numerator",
     "offset": 0,
     "size": 1,
     "type": "uint8_t",
     "elem_size": 1
    },
    {
     "name": "denominator",
     "offset": 1,
     "size": 1,
     "type": "uint8_t",
     "elem_size": 1
    },
    {
     "name": "probability",
     "offset": 4,
     "size": 4,
     "type": "float",
     "elem_size": 4
    }
   ]
  },
  "States_balance": {
   "size": 12,
   "fields": [
    {
     "name": "a",
     "offset": 0,
     "size": 4,
     "type": "float",
     "elem_size": 4
    },
    {
     "name": "b",
     "offset": 4,
     "size": 4,
     "type": "float",
     "elem_size": 4
    },
    {
     "name": "c",
     "offset": 8,
     "size": 4,
     "type": "float",
     "elem_size": 4
    }
   ]
  }
 },
 "enums": {
  "CVOutMode": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "UNIPOLAR",
     "value": 0
    },
    {
     "name": "BIPOLAR",
     "value": 1
    }
   ]
  },
  "VoltageMode": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "NORMAL",
     "value": 0
    },
    {
     "name": "ENVELOPE",
     "value": 1
    },
    {
     "name": "COUNT",
     "value": 2
    }
   ]
  },
  "EnvelopeMode": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "LOOP",
     "value": 0
    },
    {
     "name": "TRIGGER",
     "value": 1
    },
    {
     "name": "GATE",
     "value": 2
    },
    {
     "name": "COUNT",
     "value": 3
    }
   ]
  },
  "StepMode": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "VOLTAGE",
     "value": 0
    },
    {
     "name": "TIME",
     "value": 1
    },
    {
     "name": "BOTH",
     "value": 2
    },
    {
     "name": "COUNT",
     "value": 3
    }
   ]
  },
  "StepDir": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "FW",
     "value": 0
    },
    {
     "name": "RV",
     "value": 1
    },
    {
     "name": "PINGPONG",
     "value": 2
    },
    {
     "name": "COUNT",
     "value": 3
    }
   ]
  },
  "SmoothStepMode": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "OFF",
     "value": 0
    },
    {
     "name": "VOLTAGE",
     "value": 1
    },
    {
     "name": "TIME",
     "value": 2
    },
    {
     "name": "COUNT",
     "value": 3
    }
   ]
  },
  "TrgQuant": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "OFF",
     "value": 0
    },
    {
     "name": "ONE_MS",
     "value": 1
    },
    {
     "name": "TEN_MS",
     "value": 2
    },
    {
     "name": "COUNT",
     "value": 3
    }
   ]
  },
  "SmoothCurve": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "OFF",
     "value": 0
    },
    {
     "name": "LIN",
     "value": 1
    },
    {
     "name": "LOG",
     "value": 2
    },
    {
     "name": "EXP",
     "value": 3
    },
    {
     "name": "BEZIER",
     "value": 4
    },
    {
     "name": "COUNT",
     "value": 5
    }
   ]
  },
  "BitResolution": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "RES_1BIT",
     "value": 1
    },
    {
     "name": "RES_2BIT",
     "value": 2
    },
    {
     "name": "RES_3BIT",
     "value": 3
    },
    {
     "name": "RES_4BIT",
     "value": 4
    },
    {
     "name": "RES_5BIT",
     "value": 5
    },
    {
     "name": "RES_6BIT",
     "value": 6
    },
    {
     "name": "RES_7BIT",
     "value": 7
    },
    {
     "name": "RES_8BIT",
     "value": 8
    },
    {
     "name": "RES_9BIT",
     "value": 9
    },
    {
     "name": "RES_10BIT",
     "value": 10
    },
    {
     "name": "RES_11BIT",
     "value": 11
    },
    {
     "name": "RES_12BIT",
     "value": 12
    },
    {
     "name": "RES_13BIT",
     "value": 13
    },
    {
     "name": "RES_14BIT",
     "value": 14
    },
    {
     "name": "RES_15BIT",
     "value": 15
    },
    {
     "name": "RES_16BIT",
     "value": 16
    }
   ]
  },
  "TimeMode": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "TIME",
     "value": 0
    },
    {
     "name": "BPM",
     "value": 1
    },
    {
     "name": "BPM_CH1",
     "value": 2
    },
    {
     "name": "BPM_CH2",
     "value": 3
    },
    {
     "name": "BPM_CH3",
     "value": 4
    },
    {
     "name": "BPM_CH4",
     "value": 5
    },
    {
     "name": "COUNT",
     "value": 6
    }
   ]
  },
  "ClockSource": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "INTERNAL1",
     "value": 0
    },
    {
     "name": "INTERNAL2",
     "value": 1
    },
    {
     "name": "INTERNAL3",
     "value": 2
    },
    {
     "name": "INTERNAL4",
     "value": 3
    },
    {
     "name": "CLK_IN_1",
     "value": 4
    },
    {
     "name": "CLK_IN_2",
     "value": 5
    },
    {
     "name": "CLK_IN_3",
     "value": 6
    },
    {
     "name": "CLK_IN_4",
     "value": 7
    },
    {
     "name": "LOGIC_OUT1",
     "value": 8
    },
    {
     "name": "LOGIC_OUT2",
     "value": 9
    },
    {
     "name": "LOGIC_OUT3",
     "value": 10
    },
    {
     "name": "COUNT",
     "value": 11
    }
   ]
  },
  "ClockMultDiv": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "MULT_1",
     "value": 0
    },
    {
     "name": "MULT_2",
     "value": 1
    },
    {
     "name": "MULT_3",
     "value": 2
    },
    {
     "name": "MULT_4",
     "value": 3
    },
    {
     "name": "MULT_5",
     "value": 4
    },
    {
     "name": "MULT_6",
     "value": 5
    },
    {
     "name": "MULT_7",
     "value": 6
    },
    {
     "name": "MULT_8",
     "value": 7
    },
    {
     "name": "MULT_16",
     "value": 8
    },
    {
     "name": "MULT_32",
     "value": 9
    },
    {
     "name": "DIV_2",
     "value": 10
    },
    {
     "name": "DIV_3",
     "value": 11
    },
    {
     "name": "DIV_4",
     "value": 12
    },
    {
     "name": "DIV_5",
     "value": 13
    },
    {
     "name": "DIV_6",
     "value": 14
    },
    {
     "name": "DIV_7",
     "value": 15
    },
    {
     "name": "DIV_8",
     "value": 16
    },
    {
     "name": "DIV_16",
     "value": 17
    },
    {
     "name": "DIV_32",
     "value": 18
    },
    {
     "name": "COUNT",
     "value": 19
    }
   ]
  },
  "TransposeMode": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "SEMITONES",
     "value": 0
    },
    {
     "name": "SCALE_DEGREES",
     "value": 1
    },
    {
     "name": "OCTAVES",
     "value": 2
    },
    {
     "name": "CENTS",
     "value": 3
    },
    {
     "name": "COUNT",
     "value": 4
    }
   ]
  },
  "LogicOp": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "NOT",
     "value": 0
    },
    {
     "name": "AND",
     "value": 1
    },
    {
     "name": "NAND",
     "value": 2
    },
    {
     "name": "OR",
     "value": 3
    },
    {
     "name": "NOR",
     "value": 4
    },
    {
     "name": "XOR",
     "value": 5
    },
    {
     "name": "XNOR",
     "value": 6
    },
    {
     "name": "COUNTER",
     "value": 7
    },
    {
     "name": "BPM_CH1",
     "value": 8
    },
    {
     "name": "BPM_CH2",
     "value": 9
    },
    {
     "name": "BPM_CH3",
     "value": 10
    },
    {
     "name": "BPM_CH4",
     "value": 11
    },
    {
     "name": "COUNT",
     "value": 12
    }
   ]
  },
  "DistributionMode": {
   "underlying": "int",
   "size": 4,
   "values": [
    {
     "name": "OFF",
     "value": 0
    },
    {
     "name": "FREE",
     "value": 1
    },
    {
     "name": "WALK",
     "value": 2
    },
    {
     "name": "COUNT",
     "value": 3
    }
   ]
  },
  "QuantizeRounding": {
   "underlying": "unsigned char",
   "size": 1,
   "values": [
    {
     "name": "NEAREST",
     "value": 0
    },
    {
     "name": "FLOOR",
     "value": 1
    },
    {
     "name": "CEILING",
     "value": 2
    },
    {
     "name": "PROBABILITY",
     "value": 3
    },
    {
     "name": "COUNT",
     "value": 4
    }
   ]
  },
  "SequencerMode": {
   "underlying": "unsigned char",
   "size": 1,
   "values": [
    {
     "name": "TRACK",
     "value": 0
    },
    {
     "name": "HOLD",
     "value": 1
    },
    {
     "name": "ON",
     "value": 2
    },
    {
     "name": "COUNT_SEQ_MODE",
     "value": 3
    }
   ]
  },
  "PresetVersions": {
   "underlying": "unsigned short",
   "size": 4,
   "values": [
    {
     "name": "PRESET_VERSION_0",
     "value": 51966
    },
    {
     "name": "PRESET_VERSION_1",
     "value": 65281
    },
    {
     "name": "PRESET_VERSION_2",
     "value": 65282
    },
    {
     "name": "PRESET_VERSION_3",
     "value": 65283
    }
   ]
  },
  "function_id": {
   "underlying": "unsigned char",
   "size": 1,
   "values": [
    {
     "name": "FUNC_VOLTAGE_MIN",
     "value": 0
    },
    {
     "name": "FUNC_VOLTAGE_MAX",
     "value": 1
    },
    {
     "name": "FUNC_VOLTAGE_REST",
     "value": 2
    },
    {
     "name": "FUNC_VOLTAGE_STEPS",
     "value": 3
    },
    {
     "name": "FUNC_QUANTIZE_SCALE",
     "value": 4
    },
    {
     "name": "FUNC_QUANTIZE_SOURCE",
     "value": 5
    },
    {
     "name": "FUNC_QUANTIZE_ROOT",
     "value": 6
    },
    {
     "name": "FUNC_QUANTIZE_TRANSPOSE_MODE",
     "value": 7
    },
    {
     "name": "FUNC_QUANTIZE_TRANSPOSE_STEPS",
     "value": 8
    },
    {
     "name": "FUNC_GATE_LENGTH",
     "value": 9
    },
    {
     "name": "FUNC_GATE_SIZE_DEVIATION",
     "value": 10
    },
    {
     "name": "FUNC_GATE_PROBABILITY",
     "value": 11
    },
    {
     "name": "FUNC_V_PROBABILITY",
     "value": 12
    },
    {
     "name": "FUNC_V_SKIP_STEPS",
     "value": 13
    },
    {
     "name": "FUNC_V_PROB_LINEARITY",
     "value": 14
    },
    {
     "name": "FUNC_V_DIST_MODE",
     "value": 15
    },
    {
     "name": "FUNC_V_DIST_POS",
     "value": 16
    },
    {
     "name": "FUNC_V_DIST_SPREAD",
     "value": 17
    },
    {
     "name": "FUNC_V_DIST_LIN",
     "value": 18
    },
    {
     "name": "FUNC_SMOOTH_CURVE",
     "value": 19
    },
    {
     "name": "FUNC_SMOOTH_DURATION",
     "value": 20
    },
    {
     "name": "FUNC_SMOOTH_QUANTIZE_PRE_POST",
     "value": 21
    },
    {
     "name": "FUNC_SMOOTH_RESOLUTION",
     "value": 22
    },
    {
     "name": "FUNC_SMOOTH_STEP_MODE",
     "value": 23
    },
    {
     "name": "FUNC_SMOOTH_STEPS",
     "value": 24
    },
    {
     "name": "FUNC_TRIGGER_QUANT",
     "value": 25
    },
    {
     "name": "FUNC_TIME_MIN",
     "value": 26
    },
    {
     "name": "FUNC_TIME_MAX",
     "value": 27
    },
    {
     "name": "FUNC_TIME_BPM",
     "value": 28
    },
    {
     "name": "FUNC_TIME_BPM_BEAT_NOTE_NUMERATOR",
     "value": 29
    },
    {
     "name": "FUNC_TIME_BPM_BEAT_NOTE_DENOMINATOR",
     "value": 30
    },
    {
     "name": "FUNC_T_DIST_MODE",
     "value": 31
    },
    {
     "name": "FUNC_T_DIST_POS",
     "value": 32
    },
    {
     "name": "FUNC_T_DIST_SPREAD",
     "value": 33
    },
    {
     "name": "FUNC_T_DIST_LIN",
     "value": 34
    },
    {
     "name": "FUNC_CLK_SRC",
     "value": 35
    },
    {
     "name": "FUNC_CLK_MULT_DIV",
     "value": 36
    },
    {
     "name": "FUNC_STATE",
     "value": 37
    },
    {
     "name": "FUNC_STEP_ABS",
     "value": 38
    },
    {
     "name": "FUNC_STEP_VOLTAGE",
     "value": 39
    },
    {
     "name": "FUNC_STEP_TIME",
     "value": 40
    },
    {
     "name": "FUNC_STEP_BPM_NUM",
     "value": 41
    },
    {
     "name": "FUNC_STEP_BPM_DIV",
     "value": 42
    },
    {
     "name": "FUNC_STEP_NOTE",
     "value": 43
    },
    {
     "name": "FUNC_STEP_CENTS",
     "value": 44
    },
    {
     "name": "FUNC_ENV_TIME_ATTACK_MIN",
     "value": 45
    },
    {
     "name": "FUNC_ENV_TIME_ATTACK_MAX",
     "value": 46
    },
    {
     "name": "FUNC_ENV_TIME_SUSTAIN_MIN",
     "value": 47
    },
    {
     "name": "FUNC_ENV_TIME_SUSTAIN_MAX",
     "value": 48
    },
    {
     "name": "FUNC_ENV_TIME_RELEASE_MIN",
     "value": 49
    },
    {
     "name": "FUNC_ENV_TIME_RELEASE_MAX",
     "value": 50
    },
    {
     "name": "FUNC_ENV_TIME_REST_MIN",
     "value": 51
    },
    {
     "name": "FUNC_ENV_TIME_REST_MAX",
     "value": 52
    },
    {
     "name": "FUNC_ENV_TIME_SCALE_MIN",
     "value": 53
    },
    {
     "name": "FUNC_ENV_TIME_SCALE_MAX",
     "value": 54
    },
    {
     "name": "FUNC_ENV_SHAPE_ATTACK",
     "value": 55
    },
    {
     "name": "FUNC_ENV_SHAPE_RELEASE",
     "value": 56
    },
    {
     "name": "FUNC_ENVELOPE_SIZE",
     "value": 57
    },
    {
     "name": "FUNC_NOTE_PROB_C",
     "value": 58
    },
    {
     "name": "FUNC_NOTE_PROB_C_SHARP",
     "value": 59
    },
    {
     "name": "FUNC_NOTE_PROB_D",
     "value": 60
    },
    {
     "name": "FUNC_NOTE_PROB_D_SHARP",
     "value": 61
    },
    {
     "name": "FUNC_NOTE_PROB_E",
     "value": 62
    },
    {
     "name": "FUNC_NOTE_PROB_F",
     "value": 63
    },
    {
     "name": "FUNC_NOTE_PROB_F_SHARP",
     "value": 64
    },
    {
     "name": "FUNC_NOTE_PROB_G",
     "value": 65
    },
    {
     "name": "FUNC_NOTE_PROB_G_SHARP",
     "value": 66
    },
    {
     "name": "FUNC_NOTE_PROB_A",
     "value": 67
    },
    {
     "name": "FUNC_NOTE_PROB_A_SHARP",
     "value": 68
    },
    {
     "name": "FUNC_NOTE_PROB_B",
     "value": 69
    },
    {
     "name": "FUNC_NOTE_PROB_FIRST",
     "value": 70
    },
    {
     "name": "FUNC_NOTE_PROB_SECOND",
     "value": 71
    },
    {
     "name": "FUNC_NOTE_PROB_THIRD",
     "value": 72
    },
    {
     "name": "FUNC_NOTE_PROB_FOURTH",
     "value": 73
    },
    {
     "name": "FUNC_NOTE_PROB_FIFTH",
     "value": 74
    },
    {
     "name": "FUNC_NOTE_PROB_SIXTH",
     "value": 75
    },
    {
     "name": "FUNC_NOTE_PROB_SEVENTH",
     "value": 76
    },
    {
     "name": "FUNC_NOTE_PROB_EIGHTH",
     "value": 77
    },
    {
     "name": "FUNC_NOTE_PROB_NINTH",
     "value": 78
    },
    {
     "name": "FUNC_NOTE_PROB_TENTH",
     "value": 79
    },
    {
     "name": "FUNC_NOTE_PROB_ELEVENTH",
     "value": 80
    },
    {
     "name": "FUNC_NOTE_PROB_TWELFTH",
     "value": 81
    },
    {
     "name": "FUNC_NOTE_PROB_OFFSET",
     "value": 82
    },
    {
     "name": "FUNC_TIME_MODE",
     "value": 83
    },
    {
     "name": "FUNC_SEQUENCER_DIRECTION",
     "value": 84
    },
    {
     "name": "FUNC_SEQUENCER_ACTIVE",
     "value": 85
    },
    {
     "name": "FUNC_COUNT",
     "value": 86
    }
   ]
  },
  "d_function_id": {
   "underlying": "unsigned char",
   "size": 1,
   "values": [
    {
     "name": "FUNC_D_HOLD",
     "value": 0
    },
    {
     "name": "FUNC_D_ZERO",
     "value": 1
    },
    {
     "name": "FUNC_D_STATE_A",
     "value": 2
    },
    {
     "name": "FUNC_D_STATE_B",
     "value": 3
    },
    {
     "name": "FUNC_D_STATE_C",
     "value": 4
    },
    {
     "name": "FUNC_D_SEQUENCER_ACTIVE_ON",
     "value": 5
    },
    {
     "name": "FUNC_D_SEQUENCER_ACTIVE_HOLD",
     "value": 6
    },
    {
     "name": "FUNC_D_SEQUENCER_ACTIVE_TRACK",
     "value": 7
    },
    {
     "name": "FUNC_D_SEQUENCER_PLAY_PAUSE",
     "value": 8
    },
    {
     "name": "FUNC_D_SEQUENCER_PLAY_PAUSE_ALL",
     "value": 9
    },
    {
     "name": "FUNC_D_SEQUENCER_STOP",
     "value": 10
    },
    {
     "name": "FUNC_D_SEQUENCER_STOP_ALL",
     "value": 11
    },
    {
     "name": "FUNC_D_SEQUENCER_RESET",
     "value": 12
    },
    {
     "name": "FUNC_D_SEQUENCER_RESET_ALL",
     "value": 13
    },
    {
     "name": "FUNC_D_SYNC_BPM",
     "value": 14
    },
    {
     "name": "FUNC_D_V_PROB_APPLY_TO",
     "value": 15
    },
    {
     "name": "FUNC_D_CLK_FOLLOW",
     "value": 16
    },
    {
     "name": "FUNC_D_CLK_DELAY",
     "value": 17
    },
    {
     "name": "FUNC_D_CLK_EXT_MODE",
     "value": 18
    },
    {
     "name": "FUNC_D_RANDOM_CHANNEL",
     "value": 19
    },
    {
     "name": "FUNC_D_RANDOM_VOLTAGE",
     "value": 20
    },
    {
     "name": "FUNC_D_RANDOM_GATE",
     "value": 21
    },
    {
     "name": "FUNC_D_RANDOM_LOCK_1",
     "value": 22
    },
    {
     "name": "FUNC_D_RANDOM_LOCK_2",
     "value": 23
    },
    {
     "name": "FUNC_D_RANDOM_LOCK_3",
     "value": 24
    },
    {
     "name": "FUNC_D_RANDOM_PROBABILITY",
     "value": 25
    },
    {
     "name": "FUNC_D_RANDOM_VOLTAGE_DISTRIBUTION",
     "value": 26
    },
    {
     "name": "FUNC_D_RANDOM_SMOOTH_CURVE",
     "value": 27
    },
    {
     "name": "FUNC_D_RANDOM_TIME",
     "value": 28
    },
    {
     "name": "FUNC_D_RANDOM_TIME_DISTRIBUTION",
     "value": 29
    },
    {
     "name": "FUNC_D_RANDOM_CLOCK",
     "value": 30
    },
    {
     "name": "FUNC_D_COUNT",
     "value": 31
    }
   ]
  }
 },
 "consts": {
  "N_CHANNELS": 4,
  "N_STATES": 3,
  "MAX_PRESETS": 16,
  "MAX_SEQUENCER_STEPS": 32,
  "N_TIME_DIVISIONS": 11,
  "MAX_CV_ASSIGNS": 64,
  "N_LOGIC_OUTPUTS": 3,
  "MAX_LOGIC_LINES": 20,
  "N_CUSTOM_SCALES": 8,
  "PRESET_NAME_SIZE": 20,
  "QSPI_PRESET_SLOT_SIZE_V1": 20480,
  "QSPI_STORAGE_SIZE": 409600,
  "PRESET_TRAILER_MAGIC": 825308481,
  "MAX_VSTEPS": 320,
  "MAX_GATE_SKIP_STEPS": 100,
  "MAX_CV_SKIP_STEPS": 100,
  "MAX_SMOOTH_STEPS": 16,
  "MIN_SMOOTH_STEPS": 3,
  "MIN_SMOOTH_STEP_TIME_MS": 50,
  "MAX_TIME_US": 200000000,
  "BPM_MAX": 300,
  "BPM_MIN": 0.100000001,
  "N_LOGIC_INPUTS": 23
 },
 "cv": {
  "functions": [
   {
    "kind": "analog",
    "id": 0,
    "name": "FUNC_VOLTAGE_MIN",
    "short": "VMIN",
    "desc": "VOLTAGE MIN (NORMAL & ENVELOPE)",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 1,
    "name": "FUNC_VOLTAGE_MAX",
    "short": "VMAX",
    "desc": "VOLTAGE MAX (NORMAL & ENVELOPE)",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 3,
    "name": "FUNC_VOLTAGE_STEPS",
    "short": "VSTEPS",
    "desc": "VOLTAGE STEPS",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 4,
    "name": "FUNC_QUANTIZE_SCALE",
    "short": "QSCALE",
    "desc": "QUANTIZER SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 5,
    "name": "FUNC_QUANTIZE_SOURCE",
    "short": "QSRC",
    "desc": "QUANTIZER SOURCE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 6,
    "name": "FUNC_QUANTIZE_ROOT",
    "short": "QROOT",
    "desc": "QUANTIZER ROOT NOTE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 7,
    "name": "FUNC_QUANTIZE_TRANSPOSE_MODE",
    "short": "QMODE",
    "desc": "QUANTIZER TRANSPOSE MODE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 8,
    "name": "FUNC_QUANTIZE_TRANSPOSE_STEPS",
    "short": "QSTEPS",
    "desc": "QUANTIZER TRANSPOSE STEPS",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 58,
    "name": "FUNC_NOTE_PROB_C",
    "short": "NPROB C",
    "desc": "NOTE PROBABILITY C",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 59,
    "name": "FUNC_NOTE_PROB_C_SHARP",
    "short": "NPROB C#",
    "desc": "NOTE PROBABILITY C#",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 60,
    "name": "FUNC_NOTE_PROB_D",
    "short": "NPROB D",
    "desc": "NOTE PROBABILITY D",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 61,
    "name": "FUNC_NOTE_PROB_D_SHARP",
    "short": "NPROB D#",
    "desc": "NOTE PROBABILITY D#",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 62,
    "name": "FUNC_NOTE_PROB_E",
    "short": "NPROB E",
    "desc": "NOTE PROBABILITY E",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 63,
    "name": "FUNC_NOTE_PROB_F",
    "short": "NPROB F",
    "desc": "NOTE PROBABILITY F",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 64,
    "name": "FUNC_NOTE_PROB_F_SHARP",
    "short": "NPROB F#",
    "desc": "NOTE PROBABILITY F#",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 65,
    "name": "FUNC_NOTE_PROB_G",
    "short": "NPROB G",
    "desc": "NOTE PROBABILITY G",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 66,
    "name": "FUNC_NOTE_PROB_G_SHARP",
    "short": "NPROB G#",
    "desc": "NOTE PROBABILITY G#",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 67,
    "name": "FUNC_NOTE_PROB_A",
    "short": "NPROB A",
    "desc": "NOTE PROBABILITY A",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 68,
    "name": "FUNC_NOTE_PROB_A_SHARP",
    "short": "NPROB A#",
    "desc": "NOTE PROBABILITY A#",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 69,
    "name": "FUNC_NOTE_PROB_B",
    "short": "NPROB B",
    "desc": "NOTE PROBABILITY B",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 70,
    "name": "FUNC_NOTE_PROB_FIRST",
    "short": "NPROB 1ST",
    "desc": "NOTE PROBABILITY 1ST SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 71,
    "name": "FUNC_NOTE_PROB_SECOND",
    "short": "NPROB 2ND",
    "desc": "NOTE PROBABILITY 2ND SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 72,
    "name": "FUNC_NOTE_PROB_THIRD",
    "short": "NPROB 3RD",
    "desc": "NOTE PROBABILITY 3RD SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 73,
    "name": "FUNC_NOTE_PROB_FOURTH",
    "short": "NPROB 4TH",
    "desc": "NOTE PROBABILITY 4TH SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 74,
    "name": "FUNC_NOTE_PROB_FIFTH",
    "short": "NPROB 5TH",
    "desc": "NOTE PROBABILITY 5TH SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 75,
    "name": "FUNC_NOTE_PROB_SIXTH",
    "short": "NPROB 6TH",
    "desc": "NOTE PROBABILITY 6TH SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 76,
    "name": "FUNC_NOTE_PROB_SEVENTH",
    "short": "NPROB 7TH",
    "desc": "NOTE PROBABILITY 7TH SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 77,
    "name": "FUNC_NOTE_PROB_EIGHTH",
    "short": "NPROB 8TH",
    "desc": "NOTE PROBABILITY 8TH SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 78,
    "name": "FUNC_NOTE_PROB_NINTH",
    "short": "NPROB 9TH",
    "desc": "NOTE PROBABILITY 9TH SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 79,
    "name": "FUNC_NOTE_PROB_TENTH",
    "short": "NPROB 10TH",
    "desc": "NOTE PROBABILITY 10TH SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 80,
    "name": "FUNC_NOTE_PROB_ELEVENTH",
    "short": "NPROB 11TH",
    "desc": "NOTE PROBABILITY 11TH SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 81,
    "name": "FUNC_NOTE_PROB_TWELFTH",
    "short": "NPROB 12TH",
    "desc": "NOTE PROBABILITY 12TH SEMITONE IN SCALE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 82,
    "name": "FUNC_NOTE_PROB_OFFSET",
    "short": "NPROB OFFSET",
    "desc": "NOTES PROBABILITIES OFFSET",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 9,
    "name": "FUNC_GATE_LENGTH",
    "short": "GATE SIZE",
    "desc": "GATE LENGTH",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 10,
    "name": "FUNC_GATE_SIZE_DEVIATION",
    "short": "GATE SIZE DEV",
    "desc": "GATE SIZE DEVIATION",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 11,
    "name": "FUNC_GATE_PROBABILITY",
    "short": "GATE PROB",
    "desc": "GATE PROBABILITY",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 25,
    "name": "FUNC_TRIGGER_QUANT",
    "short": "TRG QUANT",
    "desc": "TRIGGER OUT AT NEW QUANTIZATION",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 12,
    "name": "FUNC_V_PROBABILITY",
    "short": "PROB",
    "desc": "PROBABILITY",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 13,
    "name": "FUNC_V_SKIP_STEPS",
    "short": "PROBSTPS",
    "desc": "PROBABILITY SKIP STEPS",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 15,
    "name": "FUNC_D_V_PROB_APPLY_TO",
    "short": "PROBAPP",
    "desc": "PROBABILITY APPLY TO (CV/CV+GATE)",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 14,
    "name": "FUNC_V_PROB_LINEARITY",
    "short": "PROBLIN",
    "desc": "PROBABILITY LINEARITY",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 15,
    "name": "FUNC_V_DIST_MODE",
    "short": "DISTMODE",
    "desc": "DISTRIBUTION MODE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 16,
    "name": "FUNC_V_DIST_POS",
    "short": "DISTPOS",
    "desc": "DISTRIBUTION POSITION",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 17,
    "name": "FUNC_V_DIST_SPREAD",
    "short": "DISTSPREAD",
    "desc": "DISTRIBUTION SPREAD (Q)",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 18,
    "name": "FUNC_V_DIST_LIN",
    "short": "DISTLIN",
    "desc": "DISTRIBUTION LINEARITY",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 19,
    "name": "FUNC_SMOOTH_CURVE",
    "short": "SMCURVE",
    "desc": "SMOOTH CURVE TYPE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 20,
    "name": "FUNC_SMOOTH_DURATION",
    "short": "SMDUR",
    "desc": "SMOOTH DURATION",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 21,
    "name": "FUNC_SMOOTH_QUANTIZE_PRE_POST",
    "short": "SMQUAPP",
    "desc": "SMOOTH QUANTIZER ORDER (PRE/POST)",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 22,
    "name": "FUNC_SMOOTH_RESOLUTION",
    "short": "SMRES",
    "desc": "SMOOTH RESOLUTION",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 23,
    "name": "FUNC_SMOOTH_STEP_MODE",
    "short": "SMSTMOD",
    "desc": "SMOOTH STEP MODE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 24,
    "name": "FUNC_SMOOTH_STEPS",
    "short": "SMSTEPS",
    "desc": "SMOOTH SKIP STEPS",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 83,
    "name": "FUNC_TIME_MODE",
    "short": "TMODE",
    "desc": "TIME MODE (TIME/BPM)",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 26,
    "name": "FUNC_TIME_MIN",
    "short": "TMIN",
    "desc": "TIME MINIMUM",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 27,
    "name": "FUNC_TIME_MAX",
    "short": "TMAX",
    "desc": "TIME MAXIMUM",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 28,
    "name": "FUNC_TIME_BPM",
    "short": "TBPM",
    "desc": "TIME BPM",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 29,
    "name": "FUNC_TIME_BPM_BEAT_NOTE_NUMERATOR",
    "short": "TBPMNN",
    "desc": "TIME BPM BEAT NOTE NUMERATOR",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 30,
    "name": "FUNC_TIME_BPM_BEAT_NOTE_DENOMINATOR",
    "short": "TBPMND",
    "desc": "TIME BPM BEAT NOTE DENOMINATOR",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 31,
    "name": "FUNC_T_DIST_MODE",
    "short": "TDMODE",
    "desc": "TIME DISTRIBUTION MODE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 32,
    "name": "FUNC_T_DIST_POS",
    "short": "TDPOS",
    "desc": "TIME DISTRIBUTION POSITION",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 33,
    "name": "FUNC_T_DIST_SPREAD",
    "short": "TDSPREAD",
    "desc": "TIME DISTRIBUTION SPREAD (Q)",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 34,
    "name": "FUNC_T_DIST_LIN",
    "short": "TDLIN",
    "desc": "TIME DISTRIBUTION LINEARITY",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 35,
    "name": "FUNC_CLK_SRC",
    "short": "CLKSRC",
    "desc": "CLOCK SOURCE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 36,
    "name": "FUNC_CLK_MULT_DIV",
    "short": "CLKMULTDIV",
    "desc": "CLOCK MULTIPLIER/DIVIDER",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 18,
    "name": "FUNC_D_CLK_EXT_MODE",
    "short": "CLKEXT",
    "desc": "EXTERNAL CLOCK MODE (LATCH/BPM)",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 16,
    "name": "FUNC_D_CLK_FOLLOW",
    "short": "CLKFOLL",
    "desc": "CLOCK FOLLOW CH (BPM/OUTPUT)",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 17,
    "name": "FUNC_D_CLK_DELAY",
    "short": "CLKUSET",
    "desc": "CLOCK USE TIME (DELAY)",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 14,
    "name": "FUNC_D_SYNC_BPM",
    "short": "SYNCBPM",
    "desc": "SYNC BPM",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 2,
    "name": "FUNC_VOLTAGE_REST",
    "short": "E REST V",
    "desc": "ENVELOPE REST VOLTAGE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 45,
    "name": "FUNC_ENV_TIME_ATTACK_MIN",
    "short": "E AMIN",
    "desc": "ENVELOPE TIME ATTACK MIN",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 46,
    "name": "FUNC_ENV_TIME_ATTACK_MAX",
    "short": "E AMAX",
    "desc": "ENVELOPE TIME ATTACK MAX",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 47,
    "name": "FUNC_ENV_TIME_SUSTAIN_MIN",
    "short": "E SMIN",
    "desc": "ENVELOPE TIME SUSTAIN MIN",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 48,
    "name": "FUNC_ENV_TIME_SUSTAIN_MAX",
    "short": "E SMAX",
    "desc": "ENVELOPE TIME SUSTAIN MAX",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 49,
    "name": "FUNC_ENV_TIME_RELEASE_MIN",
    "short": "E RMIN",
    "desc": "ENVELOPE TIME RELEASE MIN",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 50,
    "name": "FUNC_ENV_TIME_RELEASE_MAX",
    "short": "E RMAX",
    "desc": "ENVELOPE TIME RELEASE MAX",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 51,
    "name": "FUNC_ENV_TIME_REST_MIN",
    "short": "E RTMIN",
    "desc": "ENVELOPE TIME REST MIN",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 52,
    "name": "FUNC_ENV_TIME_REST_MAX",
    "short": "E RTMAX",
    "desc": "ENVELOPE TIME REST MAX",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 53,
    "name": "FUNC_ENV_TIME_SCALE_MIN",
    "short": "E SCAL MIN",
    "desc": "ENVELOPE TIME SCALE MIN",
    "handled": false
   },
   {
    "kind": "analog",
    "id": 54,
    "name": "FUNC_ENV_TIME_SCALE_MAX",
    "short": "E SCAL MAX",
    "desc": "ENVELOPE TIME SCALE MAX",
    "handled": false
   },
   {
    "kind": "analog",
    "id": 55,
    "name": "FUNC_ENV_SHAPE_ATTACK",
    "short": "E ASHAPE",
    "desc": "ENVELOPE SHAPE ATTACK",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 56,
    "name": "FUNC_ENV_SHAPE_RELEASE",
    "short": "E RSHAPE",
    "desc": "ENVELOPE SHAPE RELEASE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 57,
    "name": "FUNC_ENVELOPE_SIZE",
    "short": "E SIZE",
    "desc": "ENVELOPE SIZE SOURCE",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 0,
    "name": "FUNC_D_HOLD",
    "short": "HOLD",
    "desc": "HOLD STATE",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 1,
    "name": "FUNC_D_ZERO",
    "short": "MUTE",
    "desc": "MUTE STATE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 37,
    "name": "FUNC_STATE",
    "short": "STATE",
    "desc": "STATE SELECTION CV (A/B/C)",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 2,
    "name": "FUNC_D_STATE_A",
    "short": "STATE A",
    "desc": "STATE A",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 3,
    "name": "FUNC_D_STATE_B",
    "short": "STATE B",
    "desc": "STATE B",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 4,
    "name": "FUNC_D_STATE_C",
    "short": "STATE C",
    "desc": "STATE C",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 85,
    "name": "FUNC_SEQUENCER_ACTIVE",
    "short": "L ACTIVE",
    "desc": "LOCK ACTIVE ON/HOLD/TRACK",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 6,
    "name": "FUNC_D_SEQUENCER_ACTIVE_HOLD",
    "short": "L HOLD",
    "desc": "LOCK ACTIVE HOLD",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 5,
    "name": "FUNC_D_SEQUENCER_ACTIVE_ON",
    "short": "L ON",
    "desc": "LOCK ACTIVE ON",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 7,
    "name": "FUNC_D_SEQUENCER_ACTIVE_TRACK",
    "short": "L TRACK",
    "desc": "LOCK ACTIVE TRACK",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 84,
    "name": "FUNC_SEQUENCER_DIRECTION",
    "short": "L DIR",
    "desc": "LOCK DIRECTION FW/RV/PINGPONG",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 8,
    "name": "FUNC_D_SEQUENCER_PLAY_PAUSE",
    "short": "L PLAY",
    "desc": "LOCK PLAY/PAUSE",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 9,
    "name": "FUNC_D_SEQUENCER_PLAY_PAUSE_ALL",
    "short": "L PLAYALL",
    "desc": "LOCK PLAY/PAUSE ALL",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 10,
    "name": "FUNC_D_SEQUENCER_STOP",
    "short": "L STOP",
    "desc": "LOCK STOP",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 11,
    "name": "FUNC_D_SEQUENCER_STOP_ALL",
    "short": "L STOPALL",
    "desc": "LOCK STOP ALL",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 12,
    "name": "FUNC_D_SEQUENCER_RESET",
    "short": "L RESET",
    "desc": "LOCK RESET",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 13,
    "name": "FUNC_D_SEQUENCER_RESET_ALL",
    "short": "L RSTALL",
    "desc": "LOCK RESET ALL",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 38,
    "name": "FUNC_STEP_ABS",
    "short": "STEP SEL",
    "desc": "LOCK SELECT STEP",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 39,
    "name": "FUNC_STEP_VOLTAGE",
    "short": "STEP VOLT",
    "desc": "LOCK SELECTED STEP VOLTAGE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 40,
    "name": "FUNC_STEP_TIME",
    "short": "STEP TIME",
    "desc": "LOCK SELECTED STEP TIME (MILLIS)",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 41,
    "name": "FUNC_STEP_BPM_NUM",
    "short": "STEP NUM",
    "desc": "LOCK SELECTED STEP TIME DIV NUMERATOR",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 42,
    "name": "FUNC_STEP_BPM_DIV",
    "short": "STEP DIV",
    "desc": "LOCK SELECTED STEP TIME DIV DENOMINATOR",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 43,
    "name": "FUNC_STEP_NOTE",
    "short": "STEP NOTE",
    "desc": "LOCK SELECTED STEP NOTE",
    "handled": true
   },
   {
    "kind": "analog",
    "id": 44,
    "name": "FUNC_STEP_CENTS",
    "short": "STEP CENTS",
    "desc": "LOCK SELECTED STEP CENTS",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 19,
    "name": "FUNC_D_RANDOM_CHANNEL",
    "short": "RND CH",
    "desc": "RANDOMIZE CHANNEL",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 20,
    "name": "FUNC_D_RANDOM_VOLTAGE",
    "short": "RND VOLT",
    "desc": "RANDOMIZE VOLTAGE",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 21,
    "name": "FUNC_D_RANDOM_GATE",
    "short": "RND GATE",
    "desc": "RANDOMIZE GATE",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 22,
    "name": "FUNC_D_RANDOM_LOCK_1",
    "short": "RND LCK1",
    "desc": "RANDOMIZE LOCK PAGE 1",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 23,
    "name": "FUNC_D_RANDOM_LOCK_2",
    "short": "RND LCK2",
    "desc": "RANDOMIZE LOCK PAGE 2",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 24,
    "name": "FUNC_D_RANDOM_LOCK_3",
    "short": "RND LCK3",
    "desc": "RANDOMIZE LOCK PAGE 3",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 25,
    "name": "FUNC_D_RANDOM_PROBABILITY",
    "short": "RND PROB",
    "desc": "RANDOMIZE PROBABILITY",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 26,
    "name": "FUNC_D_RANDOM_VOLTAGE_DISTRIBUTION",
    "short": "RND VDST",
    "desc": "RANDOMIZE VOLTAGE DIST",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 27,
    "name": "FUNC_D_RANDOM_SMOOTH_CURVE",
    "short": "RND SMTH",
    "desc": "RANDOMIZE SMOOTH CURVE",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 28,
    "name": "FUNC_D_RANDOM_TIME",
    "short": "RND TIME",
    "desc": "RANDOMIZE TIME",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 29,
    "name": "FUNC_D_RANDOM_TIME_DISTRIBUTION",
    "short": "RND TDST",
    "desc": "RANDOMIZE TIME DIST",
    "handled": true
   },
   {
    "kind": "digital",
    "id": 30,
    "name": "FUNC_D_RANDOM_CLOCK",
    "short": "RND CLK",
    "desc": "RANDOMIZE CLOCK",
    "handled": true
   }
  ],
  "func_count": 86,
  "d_func_count": 31
 },
 "layout": {
  "slot_size": 20480,
  "presets_common_offset": 0,
  "calibration_factory_offset": 20480,
  "calibration_user_offset": 40960,
  "preset_base_offset": 61440,
  "image_size": 409600,
  "legacy_backup_size": 409595,
  "trailer_offset_in_slot": 20464
 }
};
    if (typeof module !== 'undefined' && module.exports) module.exports = data;
    else root.Offsets511 = data;
})(typeof window !== 'undefined' ? window : globalThis);
